# Generated by Django 5.2 on 2025-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_note_description_note_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(upload_to="media/notes/"),
        ),
    ]
